org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.1.1
minecraft_version_range=[26.1,27.1)
neo_version=26.1.1.6-beta
neo_version_range=[26,)
mod_id=gta_horse_logic
mod_name=GTA Horse Logic
mod_license=Apache 2.0
mod_version=1.0.5
mod_group_id=com.king_tajin
mod_authors=King Tajin
mod_description=Horses smoke when damaged based on health, then explode dramatically. Inspired by how cars behave in GTA.
